---
- name: Creates glances config directory
  file:
    path: /etc/glances
    owner: 'root'
    group: 'root'
    state: directory
  become_user: 'root'
  become: yes
  become_method: sudo

- name: Copy glances.conf from template
  copy:
    src: glances.conf
    dest: /etc/glances/glances.conf
  become_user: 'root'
  become: yes
  become_method: sudo