---
- name: Install Utils
  pacman:
    name: '{{ utils }}'
    state: present
  become: yes

- name: Install Utils from Arch User Repository
  script: ../../../aur/install-aur.sh {{ item }}
  with_items: '{{ utils_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur

- include: pip.yml

- name: Creates terminator config directory
  file:
    path: /home/{{ user_name }}/.config/terminator
    state: directory
  become: yes

- name: Creates terminator config directory
  file:
    path: /home/{{ user_name }}/.config/terminator
    state: directory
  become: yes

- name: Configure Terminator
  copy:
    src: ../files/terminator_config
    dest: /home/{{ user_name }}/.config/terminator/config
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
  become: yes
  become_user: '{{ user_name }}'

- name: Create bash shell aliases
  lineinfile: dest=/home/{{ user_name }}/.bashrc regexp='{{ item }}' insertafter='alias more=less' line='{{ item }}' owner='{{ user_name }}' state=present
  with_items: "{{ shell_aliases }}"
  become_user: '{{ user_name }}'
  become: yes
