---
- name: Install Developer Tools
  package:
    name: '{{ developer_stack }}'
    state: present
  become_user: 'root'
  become: yes
  become_method: sudo

- name: Install Developer Tools that require sudo
  package:
    name: '{{ developer_stack_sudo }}'
    state: present
  become_user: 'root'
  become: yes
  become_method: sudo

- include: docker-config.yml
