---
- name: Install Developer Tools
  pacman:
    name: '{{ developer_stack }}'
    state: present
  become_user: 'root'
  become: yes
  become_method: su

- name: Install Developer Tools that require sudo
  pacman:
    name: '{{ developer_stack_sudo }}'
    state: present
  become_user: 'root'
  become: yes
  become_method: su

- include: docker-config.yml
